// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBYf0Pdn70xrsc5DmZBmEjiAKBBYFoSgM',
    appId: '1:1059784534027:web:d92c90cb1adfae12643f0e',
    messagingSenderId: '1059784534027',
    projectId: 'animal-feeder-game',
    authDomain: 'animal-feeder-game.firebaseapp.com',
    storageBucket: 'animal-feeder-game.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATlKuQi6asA9LMYmU-3SeXHr1i-0hk1iA',
    appId: '1:1059784534027:android:596e5f486e613221643f0e',
    messagingSenderId: '1059784534027',
    projectId: 'animal-feeder-game',
    storageBucket: 'animal-feeder-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC29Vqc2DTXW6ls1taPVB80Wylt9fsLNW4',
    appId: '1:1059784534027:ios:747bcc6e00910f16643f0e',
    messagingSenderId: '1059784534027',
    projectId: 'animal-feeder-game',
    storageBucket: 'animal-feeder-game.appspot.com',
    iosClientId: '1059784534027-2advs2d97ltmmgeb82hn1o64p451bems.apps.googleusercontent.com',
    iosBundleId: 'com.example.animalFeederGame',
  );
}
